// <auto-generated />

using System;

namespace Theraot.Core
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<TReturn>
    {
        private Func<TReturn> _target;
        private TReturn _result;
        
        public ErsatzFunc(Func<TReturn> target)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<TReturn>();
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T, TReturn>
    {
        private Func<T, TReturn> _target;
        private TReturn _result;
        private T _obj;
        
        public ErsatzFunc(Func<T, TReturn> target, T obj)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T, TReturn>();
            _obj = obj;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_obj);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, TReturn>
    {
        private Func<T1, T2, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        
        public ErsatzFunc(Func<T1, T2, TReturn> target, T1 arg1, T2 arg2)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, TReturn>
    {
        private Func<T1, T2, T3, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        
        public ErsatzFunc(Func<T1, T2, T3, TReturn> target, T1 arg1, T2 arg2, T3 arg3)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, TReturn>
    {
        private Func<T1, T2, T3, T4, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        private T15 _arg15;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
            _arg15 = arg15;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14, _arg15);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn>
    {
        private Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> _target;
        private TReturn _result;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        private T15 _arg15;
        private T16 _arg16;
        
        public ErsatzFunc(Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            _result = default(TReturn);
            _target = target ?? FuncHelper.GetDefaultFunc<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
            _arg15 = arg15;
            _arg16 = arg16;
        }

        public TReturn Result
        {
            get
            {
                return _result;
            }
        }

        public void Invoke()
        {
            _result = _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14, _arg15, _arg16);
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction    
    {
        private Action _target;
        
        public ErsatzAction(Action target)
        {
            _target = target ?? ActionHelper.GetNoopAction();
        }

        public void Invoke()
        {
            _target.Invoke();
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T>    
    {
        private Action<T> _target;
        private T _obj;
        
        public ErsatzAction(Action<T> target, T obj)
        {
            _target = target ?? ActionHelper.GetNoopAction<T>();
            _obj = obj;
        }

        public void Invoke()
        {
            _target.Invoke(_obj);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2>    
    {
        private Action<T1, T2> _target;
        private T1 _arg1;
        private T2 _arg2;
        
        public ErsatzAction(Action<T1, T2> target, T1 arg1, T2 arg2)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2>();
            _arg1 = arg1;
            _arg2 = arg2;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3>    
    {
        private Action<T1, T2, T3> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        
        public ErsatzAction(Action<T1, T2, T3> target, T1 arg1, T2 arg2, T3 arg3)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4>    
    {
        private Action<T1, T2, T3, T4> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        
        public ErsatzAction(Action<T1, T2, T3, T4> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5>    
    {
        private Action<T1, T2, T3, T4, T5> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6>    
    {
        private Action<T1, T2, T3, T4, T5, T6> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        private T15 _arg15;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
            _arg15 = arg15;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14, _arg15);
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode]
    public struct ErsatzAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>    
    {
        private Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> _target;
        private T1 _arg1;
        private T2 _arg2;
        private T3 _arg3;
        private T4 _arg4;
        private T5 _arg5;
        private T6 _arg6;
        private T7 _arg7;
        private T8 _arg8;
        private T9 _arg9;
        private T10 _arg10;
        private T11 _arg11;
        private T12 _arg12;
        private T13 _arg13;
        private T14 _arg14;
        private T15 _arg15;
        private T16 _arg16;
        
        public ErsatzAction(Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> target, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            _target = target ?? ActionHelper.GetNoopAction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>();
            _arg1 = arg1;
            _arg2 = arg2;
            _arg3 = arg3;
            _arg4 = arg4;
            _arg5 = arg5;
            _arg6 = arg6;
            _arg7 = arg7;
            _arg8 = arg8;
            _arg9 = arg9;
            _arg10 = arg10;
            _arg11 = arg11;
            _arg12 = arg12;
            _arg13 = arg13;
            _arg14 = arg14;
            _arg15 = arg15;
            _arg16 = arg16;
        }

        public void Invoke()
        {
            _target.Invoke(_arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7, _arg8, _arg9, _arg10, _arg11, _arg12, _arg13, _arg14, _arg15, _arg16);
        }
    }
}