// <auto-generated />
/*
The template throwback.tt is responsible of importing mono tests where the behaviour will not be fully backported.

Mono code is imported this way to minimize modification of the original code,
and therefore making it easier to update the imported code with a newer version if needed.

Mono code follows different code style and conventions than the rest of this project.
No effort will be done to make it match the style - because of the aforementioned reason.

The mono code is a copy taken from mono repositories at https://github.com/mono/mono

This template does not go to Internet, nor does copy text from outside of the current repository.

The code is taken from files with a special name convention - this files are included in the repository
and taking them from github.com/mono/mono is done manually.

The throwback files from mono must be named by the original name with the following modifications:
- Replace the extension ".cs" with ".back"
- Insert the last .NET version that did not include or need the imported code.

For example ExpressionTest_Quote.cs becomes ExpressionTest_Quote.net35.back because:
- It includes tests that will not work for .NET 4.0 - so it is a throwback - hence it says ".back"
- ExpressionTest_Quote will work for .NET 3.5 or prior so it says ".net35"

List of imported files:
\System\Linq\Expressions\ExpressionTest_Call.net35.back
\System\Linq\Expressions\ExpressionTest_Quote.net35.back

*/